Controllers/ICCController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel.Data;
using DomainModel.Entity;

namespace UIJCCA.web.Controllers
{
    public class ICCController : Controller
    {
        private DataContext db = new DataContext();

        // GET: ICC
        public ActionResult Index()
        {
            var iCC = db.ICC.Include(i => i.LastMileType).Include(i => i.PostOffice).Include(i => i.TypeOfService);
            return View(iCC.ToList());
        }

        // GET: ICC/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ICC iCC = db.ICC.Find(id);
            if (iCC == null)
            {
                return HttpNotFound();
            }
            return View(iCC);
        }

        // GET: ICC/Create
        public ActionResult Create()
        {
            ViewBag.idlastMileType = new SelectList(db.LastMileType, "lastMileType", "lastMileType");
            ViewBag.idpostOffice = new SelectList(db.PostOffice, "postOffice", "postOffice");
            ViewBag.idtypeOfService = new SelectList(db.TypeOfService, "typeOfService", "typeOfService");
            return View();
        }

        // POST: ICC/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idObject,idtypeOfService,internetSpeed,idlastMileType,idpostOffice")] ICC iCC)
        {
            if (ModelState.IsValid)
            {
                db.ICC.Add(iCC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idlastMileType = new SelectList(db.LastMileType, "lastMileType", "lastMileType", iCC.idlastMileType);
            ViewBag.idpostOffice = new SelectList(db.PostOffice, "postOffice", "postOffice", iCC.idpostOffice);
            ViewBag.idtypeOfService = new SelectList(db.TypeOfService, "typeOfService", "typeOfService", iCC.idtypeOfService);
            return View(iCC);
        }

        // GET: ICC/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ICC iCC = db.ICC.Find(id);
            if (iCC == null)
            {
                return HttpNotFound();
            }
            ViewBag.idlastMileType = new SelectList(db.LastMileType, "lastMileType", "lastMileType", iCC.idlastMileType);
            ViewBag.idpostOffice = new SelectList(db.PostOffice, "postOffice", "idpost", iCC.idpostOffice);
            ViewBag.idtypeOfService = new SelectList(db.TypeOfService, "typeOfService", "typeOfService", iCC.idtypeOfService);
            return View(iCC);
        }

        // POST: ICC/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idObject,idtypeOfService,internetSpeed,idlastMileType,idpostOffice")] ICC iCC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(iCC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idlastMileType = new SelectList(db.LastMileType, "lastMileType", "lastMileType", iCC.idlastMileType);
            ViewBag.idpostOffice = new SelectList(db.PostOffice, "postOffice", "idpost", iCC.idpostOffice);
            ViewBag.idtypeOfService = new SelectList(db.TypeOfService, "typeOfService", "typeOfService", iCC.idtypeOfService);
            return View(iCC);
        }

        // GET: ICC/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ICC iCC = db.ICC.Find(id);
            if (iCC == null)
            {
                return HttpNotFound();
            }
            return View(iCC);
        }

        // POST: ICC/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ICC iCC = db.ICC.Find(id);
            db.ICC.Remove(iCC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/IncidentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel.Data;
using DomainModel.Entity;
using DomainModel.Manager;

namespace UIJCCA.web.Controllers
{
    public class IncidentsController : Controller
    {
        private DataContext db = new DataContext();
        private readonly GenericManager<Incidents> GM;

        public IncidentsController()
        {
            GM = new GenericManager<Incidents>(db);
        }
        // GET: Incidents
        public ActionResult Index()
        {
            //var incidents = db.Incidents.Include(i => i.ICC);
            var incidents = GM.GetAll().Include(i => i.ICC);
            return View(incidents.ToList());
        }

        // GET: Incidents/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incidents incidents = GM.FindBy(x=>x.idIncident == id).FirstOrDefault();
            if (incidents == null)
            {
                return HttpNotFound();
            }
            return View(incidents);
        }

        // GET: Incidents/Create
        public ActionResult Create()
        {
            ViewBag.idObject = new SelectList(db.ICC, "idObject", "idpostOffice"); // idtypeOfService
            return View();
        }

        // POST: Incidents/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idIncident,idObject,incidentOpening,IncidentClose,incidentNumberIteko,incidentNumberRT,description")] Incidents incidents)
        {
            if (ModelState.IsValid)
            {
                incidents.timestamp = DateTime.Now;
                GM.Add(incidents);
                GM.Save();
                return RedirectToAction("Index","Home");
            }

            ViewBag.idObject = new SelectList(db.ICC, "idObject", "idpostOffice", incidents.idObject);
            return View(incidents);
        }

        // GET: Incidents/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incidents incidents = GM.FindBy(x=>x.idIncident == id).FirstOrDefault();
            if (incidents == null)
            {
                return HttpNotFound();
            }
            ViewBag.idObject = new SelectList(db.ICC, "idObject", "idpostOffice", incidents.idObject);
            return View(incidents);
        }

        // POST: Incidents/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idIncident,idObject,incidentOpening,IncidentClose,incidentNumberIteko,incidentNumberRT,description")] Incidents incidents)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(incidents).State = EntityState.Modified;
                GM.Edit(incidents);
                GM.Save();
                return RedirectToAction("Home", "Index");
            }
            ViewBag.idObject = new SelectList(db.ICC, "idObject", "idpostOffice", incidents.idObject);
            return View(incidents);
        }

        // GET: Incidents/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Incidents incidents = GM.FindBy(x=>x.idIncident == id).FirstOrDefault();
            if (incidents == null)
            {
                return HttpNotFound();
            }
            return View(incidents);
        }

        // POST: Incidents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Incidents incidents = GM.FindBy(x=>x.idIncident == id).FirstOrDefault();
            db.Incidents.Remove(incidents);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel.Data;
using DomainModel.Entity;
using DomainModel.Manager;

namespace UIJCCA.web.Controllers
{
    public class PostsController : Controller
    {
        private readonly GenericManager<Post> GM;
        private DataContext db = new DataContext();

        public PostsController()
        {
            GM = new GenericManager<Post>(db);
        }
        // GET: Posts
        public ActionResult Index()
        {
            return View(GM.GetAll());
        }

        // GET: Posts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = GM.FindBy(x=> x.post == id).First();
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "post")] Post postitem)
        {
            if (ModelState.IsValid)
            {
                if (GM.Add(postitem))
                    if (GM.Save())
                        return RedirectToAction("Index");
            }

            return View(postitem);
        }

        // GET: Posts/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = GM.FindBy(x=>x.post == id).First();
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "post")] Post postitem)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(post).State = EntityState.Modified;
                //db.SaveChanges();
                if (GM.Edit(postitem))
                    if (GM.Save())
                        return RedirectToAction("Index");
            }
            return View(postitem);
        }

        // GET: Posts/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = GM.FindBy(x => x.post == id).First();//db.Post.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Post post = GM.FindBy(x=>x.post == id).First();
            GM.Delete(post);
            GM.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/RolesController.cs
using UIJCCA.web.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace UIJCCA.web.Controllers
{
    public class RolesController : Controller
    {
        private ApplicationRoleManager RoleManager
        {
            get
            {
                return HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            }
        }

        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Create(CreateRoleModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await RoleManager.CreateAsync(new ApplicationRole
                {
                    Name = model.Name,
                    Description = model.Description
                });
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ModelState.AddModelError("", "Что-то пошло не так");
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                return View(new EditRoleModel { Id = role.Id, Name = role.Name, Description = role.Description });
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<ActionResult> Edit(EditRoleModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationRole role = await RoleManager.FindByIdAsync(model.Id);
                if (role != null)
                {
                    role.Description = model.Description;
                    role.Name = model.Name;
                    IdentityResult result = await RoleManager.UpdateAsync(role);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Что-то пошло не так");
                    }
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Delete(string id)
        {
            ApplicationRole role = await RoleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await RoleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/Site.css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>*@
                @*@Html.ActionLink("UIJCCA", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })           *@
               <a href="@Url.Action("Index","Home")" class="navbar-brand" style="padding-top: 5px; padding-bottom: 5px;">
                    <img src="@Url.Content("~/images/logo.jpg")" style="height: 60px; max-height: 60px; width: auto; margin: 0 auto;"  />
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Список заявок", "Index", "Home")</li>
                    <li>@Html.ActionLink("Добавить инцидент", "Create", "Incidents")</li>
                    @if (Request.IsAuthenticated && User.IsInRole("admin"))
                    {
                    <li>
                            
                        <div class="dropdown navbar-collapse collapse">
                            <button class="btn btn-secondary dropdown-toggle navbar-btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Управление
                            </button>
                            <div class="dropdown-menu navbar-collapse" aria-labelledby="dropdownMenuButton">
                                @Html.ActionLink("Управление ОПС", "EditPostOffice", "Home", new { area = "" }, new { @class = "dropdown-item" })<br />
                                @Html.ActionLink("Управление Почтамт", "Index", "Posts", new { area = "" }, new { @class = "dropdown-item" })<br />
                                @Html.ActionLink("Управление Канал связи", "Index", "ICC", new { area = "" }, new { @class = "dropdown-item" })<br />
                                @Html.ActionLink("Управление Вид услуги", "EditTypesOfService", "Home", new { area = "" }, new { @class = "dropdown-item" })<br />
                                @Html.ActionLink("Управление Тип последней мили", "EditLastMileType", "Home", new { area = "" }, new { @class = "dropdown-item" })<br />
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="dropdown navbar-collapse collapse">
                            <button class="btn btn-secondary dropdown-toggle navbar-btn" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Пользователи
                            </button>
                            <div class="dropdown-menu navbar-collapse" aria-labelledby="dropdownMenuButton">
                                @Html.ActionLink("Управление пользователями", "UsersList", "Account", new { area = "" }, new { @class = "dropdown-item" })<br />
                                @Html.ActionLink("Управление ролями", "Index", "Roles", new { area = "" }, new { @class = "dropdown-item" })<br />                                
                            </div>
                        </div>
                    </li>
               }
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Пикалова Александра</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>