Controllers/LastMileTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DomainModel.Data;
using DomainModel.Entity;
using DomainModel.Manager;

namespace UIJCCA.web.Controllers
{
    public class LastMileTypesController : Controller
    {
        private readonly GenericManager<LastMileType> GM;
        private DataContext db = new DataContext();

        public LastMileTypesController()
        {
            GM = new GenericManager<LastMileType>(db);
        }

        // GET: LastMileTypes
        public ActionResult Index()
        {
            return View(GM.GetAll());
        }

        // GET: LastMileTypes/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LastMileType lastMileType = GM.FindBy(x=>x.lastMileType == id).FirstOrDefault();
            if (lastMileType == null)
            {
                return HttpNotFound();
            }
            return View(lastMileType);
        }

        // GET: LastMileTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LastMileTypes/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "lastMileType")] LastMileType itemlastMileType)
        {
            if (ModelState.IsValid)
            {
                GM.Add(itemlastMileType);
                GM.Save();
                return RedirectToAction("Index");
            }

            return View(itemlastMileType);
        }

        // GET: LastMileTypes/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LastMileType lastMileType = GM.FindBy(x=>x.lastMileType == id).FirstOrDefault();
            if (lastMileType == null)
            {
                return HttpNotFound();
            }
            return View(lastMileType);
        }

        // POST: LastMileTypes/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "lastMileType")] LastMileType itemlastMileType)
        {
            if (ModelState.IsValid)
            {
                //db.Entry(itemlastMileType).State = EntityState.Modified;
                GM.Edit(itemlastMileType);
                GM.Save();
                return RedirectToAction("Index");
            }
            return View(itemlastMileType);
        }

        // GET: LastMileTypes/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LastMileType lastMileType = GM.FindBy(x=>x.lastMileType == id).FirstOrDefault();
            if (lastMileType == null)
            {
                return HttpNotFound();
            }
            return View(lastMileType);
        }

        // POST: LastMileTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            LastMileType lastMileType = GM.FindBy(x => x.lastMileType == id).FirstOrDefault();
            GM.Delete(lastMileType);
            GM.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/LastMileTypes/Create.cshtml
@model DomainModel.Entity.LastMileType

@{
    ViewBag.Title = "Добавить Тип последней мили";
}

<h2>Добавить Тип последней мили</h2>


@using (Html.BeginForm("Create", "LastMileTypes", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Тип последней мили</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.lastMileType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.lastMileType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.lastMileType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LastMileTypes/Delete.cshtml
@model DomainModel.Entity.LastMileType

@{
    ViewBag.Title = "Удалить Тип последней мили";
}

<h2>Удалить Тип последней мили</h2>

<h3>Вы уверены, что хотите это удалить?</h3>
<div>
    <h4>Тип последней мили</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к списку", "Index")
        </div>
    }
</div>

Views/LastMileTypes/Details.cshtml
@model DomainModel.Entity.LastMileType

@{
    ViewBag.Title = "Детальная информация";
}

<h2>Детальная информация</h2>

<div>
    <h4>Тип последней мили</h4>
    <hr />
    <dl class="dl-horizontal">
    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.lastMileType }) |
    @Html.ActionLink("Вернуться к списку", "Index")
</p>

Views/LastMileTypes/Edit.cshtml
@model DomainModel.Entity.LastMileType

@{
    ViewBag.Title = "Редактировать Тип последней мили";
}

<h2>Редактировать Тип последней мили</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Тип последней мили</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.lastMileType)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к списку", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/LastMileTypes/Index.cshtml
@model IEnumerable<DomainModel.Entity.LastMileType>

@{
    ViewBag.Title = "Тип последней мили";
}

<h2>Тип последней мили</h2>

<p>
    @Html.ActionLink("Добавить", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.lastMileType)</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.lastMileType)
                </td>
                <td>
                    @Html.ActionLink("Редактировать", "Edit", new { id = item.lastMileType }) |
                    @Html.ActionLink("Детально", "Details", new { id = item.lastMileType }) |
                    @Html.ActionLink("Удалить", "Delete", new { id = item.lastMileType })
                </td>
            </tr>
        }
    </tbody>
</table>